ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

cspell:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/cspell/**"
frontmatter:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/frontmatter/**"
spectral:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/spectral/**"
