name: Check

on:
  pull_request:
  merge_group:

permissions:
  contents: read
  pull-requests: write # required for posting PR review comments

jobs:
  markdown-lint-check:
    name: Markdown Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      # equivalent cli: markdownlint-cli2  "**/*.md" "!**/CHANGELOG.md"  --config .markdownlint-cli2.yaml
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25 # v24.0.0
        with:
          config: .markdownlint-cli2.yaml
          fix: false
          globs: |
            **/*.md

  spelling-check:
    name: Spelling Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8.4.0
        with:
          config: .cspell.yml
          suggestions: true
          treat_flagged_words_as_errors: true
          incremental_files_only: false

  prettier-check:
    name: Prettier
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: "npm"
          node-version: "24"

      - name: Install Tools
        run: npm ci --ignore-scripts

      - name: "Format all document Check"
        run: npx prettier . --write

      - name: validate files
        run: git diff --exit-code ':*.*' || (echo 'Files are out of date, please run "npm run write:format" and commit the changes in this PR.' && exit 1)
