name: Release

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to release
        required: true
        type: choice
        options:
          - frontmatter
          - spectral
      version:
        description: Version to release
        required: true

permissions:
  id-token: write # Required for OIDC
  contents: write
  issues: write # Required for raising issues

jobs:
  build:
    name: Package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Use Node.js 24.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.x
          cache: "npm"

      # This explicitly sets the version of the npm package to match that of the tag.
      - run: npm version $RELEASE_VERSION --no-git-tag-version
        working-directory: packages/${{ github.event.inputs.package }}
        env:
          RELEASE_VERSION: ${{ github.event.inputs.version }}

      - run: npm ci --ignore-scripts
        working-directory: packages/${{ github.event.inputs.package }}

      - run: npm test
        working-directory: packages/${{ github.event.inputs.package }}

      # note if locally preparing packages you will need to explicitly set the version in package.json,
      # see for discussion https://github.com/thlorenz/doctoc/pull/289#discussion_r2649551681 for more details.
      - run: npm pack
        working-directory: packages/${{ github.event.inputs.package }}

      - name: NPM Publish
        id: publish
        run: npm publish
        working-directory: packages/${{ github.event.inputs.package }}
        continue-on-error: true

      - name: Create issue on npm publish failure
        if: ${{ steps.publish.outcome == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --title "NPM Publish step failed for release ${GITHUB_REF_NAME}" \
            --body "The NPM publish step failed for release: ${GITHUB_REF_NAME}. The npm package will need to be manually uploaded to NPM." \
            --assignee thompson-tomo
        working-directory: packages/${{ github.event.inputs.package }}

      - name: Compute tag
        id: tag
        run: |
          TAG="${{ github.event.inputs.package }}/v${{ github.event.inputs.version }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag "${{ steps.tag.outputs.tag }}"
          git push origin "${{ steps.tag.outputs.tag }}"

      - name: Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: "${{ github.event.inputs.package }} v${{ github.event.inputs.version }}"
          generate_release_notes: true
          draft: true
          working-directory: packages/${{ github.event.inputs.package }}
          files: |
            ./textlint-*.tgz
